name: Automated 24h Scraper

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
  # This opens up the secure API doorway for Appsmith
  repository_dispatch:
    types: [appsmith_trigger]

permissions:
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and Run Scraper
        working-directory: python-scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # This catches the URL sent by Appsmith and turns it into a Python variable!
          TARGET_URL: ${{ github.event.client_payload.url }}
        run: |
          pip install -r requirements.txt
          python scraper.py